### PR TITLE
Java 17 compatibility

### PR DESCRIPTION
**Pull request by v-p-b**
Burp needts special JVM arguments when using java 17, see: https://forum.portswigger.net/thread/run-burp-on-openjdk-17-5611cb564e50e

### CODE REVIEW

**Comment by ikkisoft** [comment]
@v-p-b Would you mind adjusting `burp-rest-api.bat` too?

@AlessandroCotto can do you some testing when you spare bandwidth ?

**Comment by v-p-b** [comment]
@ikkisoft It's been a while since I wrote batch scripts, but I'll take look :)

Need some time to review this CLA thing, but I'm on that too.

**Comment by v-p-b** [comment]
I was successfully nerdsniped with this one: there is a reason I didn't touch Windows batch for a while :dagger: 

I think the current Windows implementation may fail if someone uses OpenJDK/Coretto/..., but I'm not sure alternative configs on Windows are common enough to support. With the syntax figured out these are easy to add, but I'll need some sample banners for the target versions to match.

**Comment by ikkisoft** [comment]
Looks good enough from my (limited) Windows batch understanding. If you've tested, that's good. We will do some basic testing and merge soon(ish)

**Pull request merged**
